# -*- coding: utf-8 -*-
"""AOCDay11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrQU0YkxYjpceIVljUrPEDamrylwIUvW
"""

with open("input_day11.txt", "r") as f:
  lines = f.readlines()
for i in range(len(lines)):
  lines[i] = lines[i][:-1].split(" ")

machineConfig = {}
for line in lines:
  machineConfig[line[0][:3]] = line[1:]

#challenge 1
def totalPaths():
  memo = {}
  def iter(machine):
    if machine == "out":
      return 1
    else:
      if machine in memo:
        return memo[machine]
      else:
        paths = 0
        for path in machineConfig[machine]:
          paths += iter(path)
        memo[machine] = paths
        return paths
  return iter("you")
print(totalPaths())

#challenge 2
def totalPaths():
    memo = {}
    def iter(machine, dac, fft):
        if machine == "out" and dac and fft:
            return 1
        elif machine == "out":
            return 0
        key = (machine, dac, fft)
        if key in memo:
            return memo[key]
        dac_truth = dac or (machine == "dac")
        fft_truth = fft or (machine == "fft")
        paths = 0
        for path in machineConfig[machine]:
            paths += iter(path, dac_truth, fft_truth)
        memo[key] = paths
        return paths

    return iter("svr", False, False)
print(totalPaths())

