# -*- coding: utf-8 -*-
"""Day8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLQkix2w7hqiVMje9gEyFMHy_c5ouddt
"""

import math

with open("/content/input_day8.txt", "r") as f:
  lines = f.readlines()
  print(lines)

processed_list = []
for line in lines:
  split_line = line.split(',')
  processed_list.append([int(split_line[0]), int(split_line[1]), int(split_line[2])])

def distance(coord1, coord2):
  return math.sqrt((coord1[0] - coord2[0])**2 + (coord1[1] - coord2[1])**2 + (coord1[2] - coord2[2]) ** 2)

def edge(coord1, coord2):
  return [distance(coord1, coord2), [coord1, coord2]]

edgeList = []
for i in range(len(processed_list) - 1):
  for j in range(len(processed_list) - i - 1):
    edgeList.append(edge(processed_list[i], processed_list[j + i + 1]))
edgeList.sort(key=lambda x: x[0])

circuitList = []
def circuit_connector(edge):
  p1 = edge[1][0]
  p2 = edge[1][1]
  p1Contains = False
  p1List = 0
  p2Contains = False
  p2List = 0
  if len(circuitList) == 0:
    circuitList.append([p1, p2])
  for i in range(len(circuitList)):
    if p1 in circuitList[i]:
      p1Contains = True
      p1List = i
    if p2 in circuitList[i]:
      p2Contains = True
      p2List = i
  if (not p1Contains) and (not p2Contains):
    circuitList.append([p1, p2])
  elif (p1Contains) and (not p2Contains):
    circuitList[p1List].append(p2)
  elif (not p1Contains) and (p2Contains):
    circuitList[p2List].append(p1)
  else:
    if p1List == p2List:
      pass
    else:
      circuitList[p1List].extend(circuitList[p2List])
      circuitList.pop(p2List)

for i in range(1000):
  circuit_connector(edgeList[i])

circuitLength = []
for i in range(len(circuitList)):
  circuitLength.append(len(circuitList[i]))
circuitLength.sort(reverse = True)
print(circuitLength[0] * circuitLength[1] * circuitLength[2])

print(len(processed_list))

processed_list = []
for line in lines:
  split_line = line.split(',')
  processed_list.append([int(split_line[0]), int(split_line[1]), int(split_line[2])])

def distance(coord1, coord2):
  return math.sqrt((coord1[0] - coord2[0])**2 + (coord1[1] - coord2[1])**2 + (coord1[2] - coord2[2]) ** 2)

def edge(coord1, coord2):
  return [distance(coord1, coord2), [coord1, coord2]]

edgeList = []
for i in range(len(processed_list) - 1):
  for j in range(len(processed_list) - i - 1):
    edgeList.append(edge(processed_list[i], processed_list[j + i + 1]))
edgeList.sort(key=lambda x: x[0])

circuitList = []
def circuit_connector(edge):
  p1 = edge[1][0]
  p2 = edge[1][1]
  p1Contains = False
  p1List = 0
  p2Contains = False
  p2List = 0
  if len(circuitList) == 0:
    circuitList.append([p1, p2])
  for i in range(len(circuitList)):
    if p1 in circuitList[i]:
      p1Contains = True
      p1List = i
    if p2 in circuitList[i]:
      p2Contains = True
      p2List = i
  if (not p1Contains) and (not p2Contains):
    circuitList.append([p1, p2])
  elif (p1Contains) and (not p2Contains):
    circuitList[p1List].append(p2)
  elif (not p1Contains) and (p2Contains):
    circuitList[p2List].append(p1)
  else:
    if p1List == p2List:
      pass
    else:
      circuitList[p1List].extend(circuitList[p2List])
      circuitList.pop(p2List)

end = False
i = 0
while not end:
  circuit_connector(edgeList[i])
  i += 1
  if (len(circuitList) == 1 and len(circuitList[0]) == 1000):
    end = True

lastEdge = edgeList[i - 1]
print(lastEdge[1][0][0] - lastEdge[1][0][1])

print(lastEdge)

94118 * 92049