# -*- coding: utf-8 -*-
"""AOCDay10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmZXd7-D_GTQBMBIxWR1xDX4PgCpZP9k
"""

from collections import deque

def min_presses(target_bits, button_bits):
    q = deque([(0, 0)])
    memo = {0: 0}

    while q:
        state, presses = q.popleft()
        if state == target_bits:
            return presses

        for b in button_bits:
            new_state = state ^ b
            new_cost = presses + 1

            if new_state not in memo or new_cost < memo[new_state]:
                memo[new_state] = new_cost
                q.append((new_state, new_cost))

    return None

def parse_indicator(formation_str):
    inside = formation_str.strip()[1:-1]
    bitmask = 0
    for i, ch in enumerate(inside):
        if ch == '#':
            bitmask |= (1 << i)
    return bitmask

def parse_button(button_str):
    inner = button_str.strip()[1:-1]
    if not inner:
        return 0
    indices = map(int, inner.split(','))
    bitmask = 0
    for i in indices:
        bitmask |= (1 << i)
    return bitmask

with open("/content/day10_input.txt", "r") as f:
  lines = f.readlines()
for i in range(len(lines)):
  items = lines[i].split(' ')
  groupDict = {}
  groupDict["Formation"] = items[0]
  groupDict["Buttons"] = items[1:len(items) - 1]
  groupDict["Voltage"] = items[len(items) - 1][:-2]
  lines[i] = groupDict
print(lines)

total = 0
for machine in lines:
  target = parse_indicator(machine["Formation"].strip())
  button_masks = [parse_button(b) for b in machine["Buttons"]]
  ans = min_presses(target, button_masks)
  total += ans
print(total)

import re

def parse_button_list(lst):
    result = []
    for button in lst:
        nums = re.findall(r"\d+", button)
        nums = list(map(int, nums))
        result.append(nums)
    return result

def parse_voltage(s):
    nums = re.findall(r"\d+", s)
    return list(map(int, nums))

def pad_lists(data, size):
    padded = []
    for lst in data:
        returnList = []
        for i in range(size):
          if i in lst:
            returnList.append(1)
          else:
            returnList.append(0)
        padded.append(returnList)
    return padded

def pad_buttons(voltage, buttonList):
  return pad_lists(buttonList, len(voltage))

machine1 = lines[0]
volt = parse_voltage(machine1["Voltage"])
buttonList = parse_button_list(machine1["Buttons"])
print(buttonList)
buttonList = pad_buttons(volt, buttonList)
print(buttonList)
print(volt)

from ortools.linear_solver import pywraplp

def solver(target, buttons):
  m = len(buttons)
  n = len(target)

  solver = pywraplp.Solver.CreateSolver("SCIP")
  x = [solver.IntVar(0, solver.infinity(), f"x{i}") for i in range(m)]

  for j in range(n):
      solver.Add(sum(buttons[i][j] * x[i] for i in range(m)) == target[j])

  solver.Minimize(sum(x))
  status = solver.Solve()
  if status == pywraplp.Solver.OPTIMAL:
    acc = 0
    for i in range(m):
      acc += x[i].solution_value()
    return acc
  else:
    print("No Solutions Found")

total = 0
for machine in lines:
  volt = parse_voltage(machine["Voltage"])
  buttonList = parse_button_list(machine["Buttons"])
  buttonList = pad_buttons(volt, buttonList)
  total += solver(volt, buttonList)
print(total)